--------------------------------------------------------
--  Fichier créé - jeudi-novembre-04-2021   
--------------------------------------------------------
DROP TABLE "KHALED"."AGENTS";
DROP TABLE "KHALED"."CLIENTS";
DROP TABLE "KHALED"."DELIVERIES";
DROP TABLE "KHALED"."PRODUCT";
DROP TABLE "KHALED"."TRUCK";
--------------------------------------------------------
--  DDL for Table AGENTS
--------------------------------------------------------

  CREATE TABLE "KHALED"."AGENTS" 
   (	"CIN" CHAR(8 BYTE), 
	"NAME" CHAR(20 BYTE), 
	"ADMISSIONDATE" DATE, 
	"NBR_ABSENCES" NUMBER, 
	"ADRESS" CHAR(50 BYTE), 
	"POSITION" NUMBER(*,0), 
	"SALARY" FLOAT(126), 
	"EMAIL" CHAR(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTS
--------------------------------------------------------

  CREATE TABLE "KHALED"."CLIENTS" 
   (	"CLIENT_CIN" CHAR(8 BYTE), 
	"NAME_CLIENT" CHAR(20 BYTE), 
	"PHONE_NUM" LONG, 
	"BIRTHDAY" DATE, 
	"GENDER" NUMBER(*,0), 
	"EMAIL" CHAR(40 BYTE), 
	"ADRESS" CHAR(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DELIVERIES
--------------------------------------------------------

  CREATE TABLE "KHALED"."DELIVERIES" 
   (	"PACKAGE_NUM" NUMBER(*,0), 
	"DELIVERY_DATE" DATE, 
	"PAYEMENT" FLOAT(126), 
	"DESTINATION" CHAR(20 BYTE), 
	"CLIENT_CIN" CHAR(8 BYTE), 
	"TRUCK_ID" CHAR(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "KHALED"."PRODUCT" 
   (	"PRODUCT_ID" CHAR(8 BYTE), 
	"PROVIDER_NAME" CHAR(20 BYTE), 
	"QUANTITY" NUMBER(*,0), 
	"PRICE" FLOAT(126), 
	"PROVIDER_EMAIL" CHAR(40 BYTE), 
	"BILL" FLOAT(126), 
	"PRODUUCT_STATUS" NUMBER(*,0), 
	"PRODUCT_NAME" CHAR(20 BYTE), 
	"PACKAGE_NUM" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRUCK
--------------------------------------------------------

  CREATE TABLE "KHALED"."TRUCK" 
   (	"TRUCK_ID" CHAR(8 BYTE), 
	"TRUCT_STATE" NUMBER, 
	"CIN" CHAR(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.AGENTS
SET DEFINE OFF;
REM INSERTING into SYSTEM.CLIENTS
SET DEFINE OFF;
REM INSERTING into SYSTEM.DELIVERIES
SET DEFINE OFF;
REM INSERTING into SYSTEM.PRODUCT
SET DEFINE OFF;
REM INSERTING into SYSTEM.TRUCK
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index AGENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALED"."AGENTS_PK" ON "KHALED"."AGENTS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALED"."CLIENTS_PK" ON "KHALED"."CLIENTS" ("CLIENT_CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DELIVERIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALED"."DELIVERIES_PK" ON "KHALED"."DELIVERIES" ("PACKAGE_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TRUCK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "KHALED"."TRUCK_PK" ON "KHALED"."TRUCK" ("TRUCK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AGENTS
--------------------------------------------------------

  ALTER TABLE "KHALED"."AGENTS" ADD CONSTRAINT "AGENTS_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KHALED"."AGENTS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."AGENTS" MODIFY ("SALARY" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."AGENTS" MODIFY ("POSITION" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."AGENTS" MODIFY ("ADRESS" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."AGENTS" MODIFY ("NBR_ABSENCES" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."AGENTS" MODIFY ("ADMISSIONDATE" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."AGENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."AGENTS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTS
--------------------------------------------------------

  ALTER TABLE "KHALED"."CLIENTS" MODIFY ("ADRESS" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."CLIENTS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."CLIENTS" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."CLIENTS" MODIFY ("BIRTHDAY" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."CLIENTS" MODIFY ("PHONE_NUM" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."CLIENTS" MODIFY ("NAME_CLIENT" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."CLIENTS" MODIFY ("CLIENT_CIN" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."CLIENTS" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("CLIENT_CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DELIVERIES
--------------------------------------------------------

  ALTER TABLE "KHALED"."DELIVERIES" ADD CONSTRAINT "DELIVERIES_PK" PRIMARY KEY ("PACKAGE_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KHALED"."DELIVERIES" MODIFY ("CLIENT_CIN" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."DELIVERIES" MODIFY ("PAYEMENT" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."DELIVERIES" MODIFY ("DELIVERY_DATE" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."DELIVERIES" MODIFY ("PACKAGE_NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "KHALED"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID") DISABLE;
  ALTER TABLE "KHALED"."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."PRODUCT" MODIFY ("PRODUUCT_STATUS" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."PRODUCT" MODIFY ("BILL" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."PRODUCT" MODIFY ("PROVIDER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."PRODUCT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."PRODUCT" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."PRODUCT" MODIFY ("PROVIDER_NAME" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRUCK
--------------------------------------------------------

  ALTER TABLE "KHALED"."TRUCK" ADD CONSTRAINT "TRUCK_PK" PRIMARY KEY ("TRUCK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "KHALED"."TRUCK" MODIFY ("TRUCT_STATE" NOT NULL ENABLE);
  ALTER TABLE "KHALED"."TRUCK" MODIFY ("TRUCK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DELIVERIES
--------------------------------------------------------

  ALTER TABLE "KHALED"."DELIVERIES" ADD CONSTRAINT "DELIVERIES_FK1" FOREIGN KEY ("TRUCK_ID")
	  REFERENCES "KHALED"."TRUCK" ("TRUCK_ID") ENABLE;
  ALTER TABLE "KHALED"."DELIVERIES" ADD CONSTRAINT "DELIVERIES_FK2" FOREIGN KEY ("CLIENT_CIN")
	  REFERENCES "KHALED"."CLIENTS" ("CLIENT_CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "KHALED"."PRODUCT" ADD CONSTRAINT "PRODUCT_FK1" FOREIGN KEY ("PACKAGE_NUM")
	  REFERENCES "KHALED"."DELIVERIES" ("PACKAGE_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRUCK
--------------------------------------------------------

  ALTER TABLE "KHALED"."TRUCK" ADD CONSTRAINT "TRUCK_FK1" FOREIGN KEY ("CIN")
	  REFERENCES "KHALED"."AGENTS" ("CIN") ENABLE;
